services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bilionario-app
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
