services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bilionario-app:latest
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
